### PR TITLE
Use Suave from a console application

### PR DESCRIPTION
**Pull request by panesofglass**
@kolektiv @haf looks like I may have my routing wrong. What am I missing?

### CODE REVIEW

**Comment by haf** [comment]
Sorry I don't know. Nothing particular from my point of view.

**Comment by panesofglass** [comment]
@haf thanks for looking. I just pushed an attempt at running the latest stable Freya 2.0 on Suave with similar results, though unlike #3, Freya _does_ run on HttpListener. I think this is expected, right, @kolektiv?

**Comment by haf** [comment]
Why is that expected? I thought we validated that Freya worked, or what am I missing?

**Comment by kolektiv** [comment]
I did think that Freya 3 (prereleases still of course) was happy enough on
Suave. Does it seem like the routing is actually hitting a handler?
(Breakpoint?)

**Comment by panesofglass** [comment]
@kolektiv I cannot hit a breakpoint with either Suave or Katana.

**Comment by panesofglass** [comment]
@haf I don't think Freya 2 works on Suave. Is that right, @kolektiv? Would it be possible to port that to Freya 2?

**Comment by haf** [comment]
Ah, we tested only v3. Why not use that?

**Comment by panesofglass** [comment]
@haf that's what I was trying. I'll try earlier versions b/c the latest doesn't appear to respond.

**Pull request closed without merging**
