### PR TITLE
Attempt to update to Freya 3.0.0-b*

### PR DESCRIPTION
**Pull request by panesofglass**
@kolektiv, I cannot get Freya 3 to respond to requests. Help is much appreciated.

### CODE REVIEW

**Comment by kolektiv** [comment]
To start, I changed my dependencies to be less specific/granular, just requiring

```
nuget Suave ~> 1
nuget Freya ~> 3.0.0-b
```

And then ran `paket install`, which got me the latest Arachne, etc. which should be correct. What should I run to start to test if it's working?

**Comment by panesofglass** [comment]
Try DomainModeling.sln

**Comment by panesofglass** [comment]
Hmm, not quite that simple. You need to run create-db.sql on (localdb)\ProjectsV12 first. Then call http://localhost:7000/calc?start=Houston, TX&dest=Beaumont, TX (after url encoding that query string)

**Comment by kolektiv** [comment]
I don't even have a localdb I'm afraid! :)

**Comment by panesofglass** [comment]
You should. I think VS installs that.

**Comment by panesofglass** [comment]
Looks like the issue is that I was not properly matching the expected query parameters.

**Comment by panesofglass** [comment]
Thank you, @kolektiv and @haf, for looking into this and helping me out. I now have Freya and Suave running via FsReveal, complete with a form through which you interact with a Freya API!

I also got this running from the FsReveal script! It's helped me bypass a bug in Freya's CORS implementation for my upcoming talk!
1. [Freya app included in FsReveal slides](https://github.com/panesofglass/domain-modeling/blob/master/slides/index.fsx#L1020-L1091)
2. [Include FsReveal script](https://github.com/panesofglass/domain-modeling/blob/master/build.fsx#L9)
3. [Mount Freya app in Suave server](https://github.com/panesofglass/domain-modeling/blob/master/build.fsx#L125)

Thank you, @tpetricek, for the idea of running these things in slides and the Literate mode of FSharp.Formatting. My talk would be a little less awesome were it not for these things.

Thank you, @cloudroutine, for helping me learn how to reference values from loaded script files!

cc: @sergey-tihon in case you think this neat enough to include in your next F# Weekly.

**Comment by panesofglass** [comment]
See the updated README for more info.

**Pull request merged**
